language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install libxtst-dev
  - sudo apt-get install libxkbfile-dev
  - wget --no-check-certificate https://launchpad.net/virtkey/0.63/0.63.0/+download/virtkey-0.63.0.tar.gz -O virtkey-0.63.0.tar.gz
  - tar -xzvf virtkey-0.63.0.tar.gz
  - cd virtkey-0.63.0 && python setup.py install && cd ..
install:
  - python setup.py install
script:
  - python test/test_musca.py
